# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-26 22:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('djangocms_style', '0007_style_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListStyle',
            fields=[
                ('style_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='djangocms_style.Style')),
                ('list_type', models.CharField(choices=[('ol', 'Ordered'), ('ul', 'Unordered')], default='ul', max_length=2)),
            ],
            options={
                'abstract': False,
            },
            bases=('djangocms_style.style',),
        ),
    ]
